package models

import "time"

// User represents an application user account.
type User struct {
	ID        int
	Email     string
	Username  string
	Password  string
	CreatedAt time.Time
}

// Post represents forum post data plus derived view fields for templates.
type Post struct {
	ID            int
	UserID        int
	Author        string // Για ευκολία στο template
	Title         string
	Content       string
	ImagePath     string
	Categories    []string
	Likes         int
	Dislikes      int
	CommentCount  int
	CreatedAt     time.Time
	UpdatedAt     time.Time
	FormattedTime string
	CanManage     bool
}

// Comment represents a post comment plus derived fields used in UI rendering.
type Comment struct {
	ID            int
	PostID        int
	UserID        int
	Author        string
	Content       string
	Likes         int
	Dislikes      int
	CreatedAt     time.Time
	UpdatedAt     time.Time
	FormattedTime string
	PostTitle     string
	PostAuthor    string
	CanManage     bool
}

// Notification represents a user notification event generated by interactions.
type Notification struct {
	ID        int
	ActorID   int
	ActorName string
	UserID    int
	PostID    int
	PostTitle string
	Type      string
	IsRead    bool
	CreatedAt time.Time
}

// ActivityVote represents a vote event in the user's activity feed.
type ActivityVote struct {
	ID            int
	Type          int
	TargetType    string
	TargetID      int
	TargetContent string
	PostID        int
	PostTitle     string
	CreatedAt     time.Time
}

// PageData is a shared template payload used by legacy views.
type PageData struct {
	IsLoggedIn         bool
	User               User
	Posts              []Post
	Post               Post
	Comments           []Comment
	Categories         []string
	Notifications      []Notification
	UnreadNotifications int
	ActivityPosts      []Post
	ActivityVotes      []ActivityVote
	ActivityComments   []Comment
	ManagedComments    []Comment
	FormAction         string
	SubmitLabel        string
	PageTitle          string
	SelectedCategories map[string]bool
	Success            string
	Error              string
}
